# ./docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: web
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - js_fortune_teller_web

  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./docker/mongodb/data:/data/db
    networks:
      - js_fortune_teller_web

  mongodb-ui:
    image: mongo-express:latest
    container_name: mongodb-ui
    ports:
      - "${MONGO_UI_PORT}:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_URL: "${MONGODB_URI}"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "${ME_CONFIG_MONGODB_ENABLE_ADMIN}"
      ME_CONFIG_SITE_SESSIONSECRET: "${ME_CONFIG_SITE_SESSIONSECRET}"
      ME_CONFIG_BASICAUTH: "${ME_CONFIG_BASICAUTH}"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
    depends_on:
      - mongodb
    networks:
      - js_fortune_teller_web

networks:
  js_fortune_teller_web:
    driver: bridge